# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_waiting.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QWaiting(object):
    def setupUi(self, QWaiting):
        QWaiting.setObjectName("QWaiting")
        QWaiting.resize(294, 106)
        self.label = QtWidgets.QLabel(QWaiting)
        self.label.setGeometry(QtCore.QRect(70, 10, 171, 41))
        self.label.setMaximumSize(QtCore.QSize(200, 200))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(QWaiting)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(QWaiting)
        QtCore.QMetaObject.connectSlotsByName(QWaiting)

    def retranslateUi(self, QWaiting):
        _translate = QtCore.QCoreApplication.translate
        QWaiting.setWindowTitle(_translate("QWaiting", "Form"))
        self.label_2.setText(_translate("QWaiting", "正在拼接中，请耐心等待"))
import resource_rc
